# Generated by Django 3.0.5 on 2020-05-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fuente_idioma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('acronimo', models.CharField(max_length=15, verbose_name='Acrónimo')),
                ('fabricante', models.CharField(max_length=30, verbose_name='Fabricante')),
            ],
        ),
    ]
