# Generated by Django 3.0.5 on 2020-05-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_plataforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('subtitulo', models.TextField(verbose_name='Subtítulo')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fuente')),
                ('plataforma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Plataforma')),
            ],
        ),
    ]
