# Generated by Django 3.0.5 on 2020-05-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200505_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='plataforma',
            field=models.ManyToManyField(null=True, to='main.Plataforma'),
        ),
    ]
