# Generated by Django 3.0.5 on 2020-05-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200505_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='enlace',
            field=models.CharField(default='http:/vandal.net', max_length=250, verbose_name='enlace'),
            preserve_default=False,
        ),
    ]
