# Generated by Django 3.0.5 on 2020-05-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_actualizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='nombre',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='nombres',
            field=models.CharField(default='plataformas', max_length=300, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
