# Generated by Django 3.0.5 on 2020-05-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200505_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(default='2010-01-01', verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='nombres',
            field=models.CharField(max_length=300, verbose_name='Nombres'),
        ),
    ]
