# Generated by Django 3.0.5 on 2020-05-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200505_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(blank=True, verbose_name='Fecha'),
        ),
    ]
