# Generated by Django 3.2 on 2021-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200505_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
